project_id = "ahdtenixvhgncwaglxui"

[functions.ai-job-recommendations]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.personalized-feed]
verify_jwt = true

[functions.rewrite-post]
verify_jwt = false