import React,{useCallback,useEffect,useMemo,useState} from 'react';
import { CalendarDays, Check, Copy, Megaphone, Plus, Sparkles, Target, Users, Zap } from 'lucide-react';
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { useBusinessContext } from '@/contexts/BusinessContext';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
export default function BusinessGrowth(){
 const {currentBusiness}=useBusinessContext(); const bid=currentBusiness?.id; const [leads,setLeads]=useState([]); const [plan,setPlan]=useState(null); const [offer,setOffer]=useState(''); const [audience,setAudience]=useState('My ideal customers'); const [objective,setObjective]=useState('Generate qualified enquiries'); const [campaign,setCampaign]=useState(''); const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{if(!bid)return; const [l,p]=await Promise.all([supabase.from('business_leads').select('id,name,status,source,next_follow_up_at,follow_up_status').eq('business_id',bid).order('created_at',{ascending:false}).limit(500),supabase.from('business_growth_plans').select('*').eq('business_id',bid).eq('status','active').order('week_start',{ascending:false}).limit(1).maybeSingle()]);setLeads(l.data||[]);setPlan(p.data||null)},[bid]); useEffect(()=>{load()},[load]);
 const leak=useMemo(()=>leads.filter(l=>l.next_follow_up_at&&new Date(l.next_follow_up_at)<new Date()&&!['closed_won','closed_lost'].includes(l.status)),[leads]);
 const generate=async()=>{
  if(!bid)return;
  setSaving(true);
  try{
   const week=new Date(); week.setDate(week.getDate()-((week.getDay()+6)%7));
   const weekStart=week.toISOString().slice(0,10);
   const context=`Business: ${currentBusiness?.name||'Business'}; industry: ${currentBusiness?.industry||'unknown'}; category: ${currentBusiness?.category||'unknown'}; audience: ${audience}; offer: ${offer||'not defined'}; objective: ${objective}; current leads: ${leads.length}; overdue follow-ups: ${leak.length}.`;
   const {data:ai,error:aiError}=await supabase.functions.invoke('ai-chat',{body:{mode:'business-growth',message:'Create my 7-day growth plan.',context}});
   if(aiError)throw aiError;
   let parsed; try { parsed=JSON.parse(ai?.response||''); } catch { throw new Error('AI returned an invalid growth plan. Please try again.'); }
   const payload={business_id:bid,week_start:weekStart,objective,audience,offer,plan:parsed,status:'active',created_by:null};
   const {data,error}=await supabase.from('business_growth_plans').upsert(payload,{onConflict:'business_id,week_start'}).select().single();
   if(error)throw error;
   await supabase.from('business_usage_events').insert({business_id:bid,usage_type:'growth_plan_generation',units:1,metadata:{source:'business-growth'}});
   setPlan(data); toast.success('AI growth plan is ready');
  }catch(e){toast.error(e?.message||'Could not create AI plan')}finally{setSaving(false)}
 };
 const createCampaign=async()=>{if(!bid||!campaign.trim())return;setSaving(true);try{const tracking=`bb_${crypto.randomUUID().replaceAll('-','').slice(0,16)}`;const {error}=await supabase.from('business_growth_campaigns').insert({business_id:bid,growth_plan_id:plan?.id||null,name:campaign,objective,audience,offer,tracking_code:tracking,content:{message:`${offer||'Our offer'} — ${campaign}. Message us to enquire.`},status:'draft'});if(error)throw error;await supabase.from('business_usage_events').insert({business_id:bid,usage_type:'campaign_created',units:1});toast.success('Campaign draft created');setCampaign('');}catch(e){toast.error(e.message||'Could not create campaign')}finally{setSaving(false)}};
 const copyPlan=async()=>{if(!plan)return;const days=plan.plan?.days||[];await navigator.clipboard.writeText(days.map(x=>`${x.day}: ${x.focus}\n${x.action}\nCTA: ${x.cta}`).join('\n\n'));toast.success('7-day plan copied')};
 return <div className="p-4 md:p-6 max-w-[1400px] mx-auto space-y-5"><div><p className="text-xs text-primary font-semibold uppercase tracking-[.15em]">Growth Engine</p><h1 className="text-2xl md:text-3xl font-bold">Turn attention into revenue.</h1><p className="text-sm text-muted-foreground mt-1">One simple loop: plan → campaign → leads → follow-up → revenue.</p></div>
 <div className="grid md:grid-cols-3 gap-3"><Card><CardContent className="p-4"><Target className="w-4 h-4 text-primary"/><p className="text-2xl font-bold mt-2">{leads.length}</p><p className="text-xs text-muted-foreground">Leads captured</p></CardContent></Card><Card><CardContent className="p-4"><Zap className="w-4 h-4 text-amber-500"/><p className="text-2xl font-bold mt-2">{leak.length}</p><p className="text-xs text-muted-foreground">Lead leaks / overdue follow-ups</p></CardContent></Card><Card><CardContent className="p-4"><Sparkles className="w-4 h-4 text-primary"/><p className="text-2xl font-bold mt-2">{plan?'Active':'Not started'}</p><p className="text-xs text-muted-foreground">7-day growth engine</p></CardContent></Card></div>
 <div className="grid lg:grid-cols-[1fr_1.4fr] gap-5"><Card><CardHeader><CardTitle className="text-base flex items-center gap-2"><Sparkles className="w-4 h-4"/>Create this week's plan</CardTitle></CardHeader><CardContent className="space-y-3"><div><label className="text-xs font-medium">Objective</label><Input className="mt-1" value={objective} onChange={e=>setObjective(e.target.value)}/></div><div><label className="text-xs font-medium">Audience</label><Input className="mt-1" value={audience} onChange={e=>setAudience(e.target.value)}/></div><div><label className="text-xs font-medium">Offer / service</label><Textarea className="mt-1" value={offer} onChange={e=>setOffer(e.target.value)} placeholder="e.g. Diwali package, consultation, new product"/></div><Button className="w-full" onClick={generate} disabled={saving}><CalendarDays className="w-4 h-4 mr-2"/>{saving?'Building…':'Build 7-Day Growth Plan'}</Button></CardContent></Card>
 <Card><CardHeader><div className="flex items-center justify-between"><div><CardTitle className="text-base">7-Day plan</CardTitle><p className="text-xs text-muted-foreground">Small actions every day, measured by enquiries and revenue.</p></div>{plan&&<Button variant="outline" size="sm" onClick={copyPlan}><Copy className="w-3.5 h-3.5 mr-1"/>Copy</Button>}</div></CardHeader><CardContent>{plan?<div className="space-y-2">{(plan.plan?.days||[]).map((x,i)=><div key={i} className="flex gap-3 rounded-xl border p-3"><div className="w-7 h-7 rounded-full bg-primary/10 flex items-center justify-center text-xs font-semibold">{i+1}</div><div><p className="text-sm font-medium">{x.day} · {x.focus}</p><p className="text-xs text-muted-foreground mt-1">{x.action}</p><p className="text-[11px] text-primary mt-1">CTA: {x.cta}</p></div></div>)}</div>:<div className="py-12 text-center text-sm text-muted-foreground"><Sparkles className="w-7 h-7 mx-auto mb-2 opacity-50"/>Create your first plan. No agency, spreadsheet or marketing jargon.</div>}</CardContent></Card></div>
 <Card><CardHeader><CardTitle className="text-base flex items-center gap-2"><Megaphone className="w-4 h-4"/>Campaign starter</CardTitle></CardHeader><CardContent><div className="grid md:grid-cols-[1fr_1fr_auto] gap-3"><Input placeholder="Campaign name" value={campaign} onChange={e=>setCampaign(e.target.value)}/><Input placeholder="Offer / CTA" value={offer} onChange={e=>setOffer(e.target.value)}/><Button onClick={createCampaign} disabled={!campaign.trim()||saving}><Plus className="w-4 h-4 mr-2"/>Create draft</Button></div><p className="text-[11px] text-muted-foreground mt-3">Publishing to external channels requires the relevant channel connection. BizBase keeps the campaign, tracking and lead flow in one place.</p></CardContent></Card>
 <Card className={leak.length?'border-destructive/30':''}><CardContent className="p-5"><div className="flex items-center gap-3"><Users className="w-5 h-5 text-primary"/><div className="flex-1"><p className="font-semibold">Lead Leak Detector</p><p className="text-xs text-muted-foreground">Leads with overdue follow-ups should never disappear from your pipeline.</p></div><Badge variant={leak.length?'destructive':'secondary'}>{leak.length} overdue</Badge></div>{leak.length>0&&<div className="mt-4 grid md:grid-cols-2 gap-2">{leak.slice(0,6).map(l=><div key={l.id} className="rounded-xl border p-3 flex items-center justify-between"><div><p className="text-sm font-medium">{l.name}</p><p className="text-xs text-muted-foreground">{l.source||'Direct'} · follow-up overdue</p></div><Check className="w-4 h-4 text-destructive"/></div>)}</div>}</CardContent></Card>
 </div>;
}
