import React,{useMemo} from 'react';
import { CalendarClock, CheckCircle2, CreditCard, Download, ShieldCheck, Zap } from 'lucide-react';
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { useBusinessContext } from '@/contexts/BusinessContext';
import { toast } from 'sonner';

export default function BusinessBilling(){
 const {currentBusiness}=useBusinessContext();
 const days=useMemo(()=>currentBusiness?.trial_ends_at?Math.max(0,Math.ceil((new Date(currentBusiness.trial_ends_at)-new Date())/86400000)):30,[currentBusiness]);
 return <div className="p-4 md:p-6 max-w-[1000px] mx-auto space-y-5"><div><p className="text-xs text-primary font-semibold uppercase tracking-[.15em]">Simple billing</p><h1 className="text-2xl font-bold">Use first. Pay later.</h1><p className="text-sm text-muted-foreground mt-1">30 days free. No card. No auto-pay. After the trial, paid features can be used on a transparent usage-based plan.</p></div>
 <Card className="border-primary/20"><CardContent className="p-6"><div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><Badge variant="secondary"><CalendarClock className="w-3 h-3 mr-1"/> {days} days left in free access</Badge><h2 className="text-2xl font-bold mt-3">BizBase Growth Control</h2><p className="text-sm text-muted-foreground mt-1">Core business data and the basic growth loop remain simple and transparent.</p></div><div className="text-right"><p className="text-4xl font-bold">₹0</p><p className="text-xs text-muted-foreground">during trial</p></div></div><div className="grid sm:grid-cols-2 gap-3 mt-6">{['Business Pulse','Lead capture & CRM','Lead Leak Detector','7-Day Growth Plans','Customers & business data','CSV import / export','No credit card','No automatic charge'].map(x=><div key={x} className="flex items-center gap-2 text-sm"><CheckCircle2 className="w-4 h-4 text-emerald-600"/>{x}</div>)}</div></CardContent></Card>
 <div className="grid md:grid-cols-2 gap-4"><Card><CardHeader><CardTitle className="text-base flex items-center gap-2"><Zap className="w-4 h-4"/>Pay for usage</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">After the free period, advanced execution can be metered by real usage—AI generations, campaign execution, automation runs and connected-channel activity—rather than forcing every business into the same heavy plan.</p><Button className="mt-4" onClick={()=>toast.info('Usage billing will be activated when your trial ends. No automatic payment is taken.')}>View usage model</Button></CardContent></Card><Card><CardHeader><CardTitle className="text-base flex items-center gap-2"><ShieldCheck className="w-4 h-4"/>Your data stays portable</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">BizBase is designed to earn retention through useful workflows, history and automation—not by locking business data behind a wall.</p><Button variant="outline" className="mt-4" onClick={()=>toast.info('Use the Export button in Business Pulse to export your lead data.') }><Download className="w-4 h-4 mr-2"/>Export data</Button></CardContent></Card></div>
 </div>
}
